void checkFunctionSemantics(TreeNode root, int functionIndex);
int evalArithmeticExpressionType(TreeNode root,int functionIndex);
void checkAssignmentStatement(TreeNode root, int functionIndex);
int getGlobalIndex(char* varName);
int getVarIndex(int funcIndex,char* string);
int getType(int functionIndex,TreeNode root);
char* getTypeString(int type);
void checkFunctionCallSemantics(TreeNode root, int functionIndex);
void checkBooleanSemantics(TreeNode root,int functionIndex);
void checkIterativeStatementSemantics(TreeNode root,int functionIndex);
int checkIfVarUpdated(char* name,TreeNode stmtNode);
int isValidWhile(TreeNode root,TreeNode stmtNode);
void checkConditionalStatementSemantics(TreeNode root,int functionIndex);
void checkStatementSemantics(TreeNode root,int functionIndex);
void checkIOStatementSemantics(TreeNode root,int functionIndex);
void semanticAnalyser(TreeNode root);
void checkReturnStatementSemantics(TreeNode root,int functionIndex);
